services:
  web:
    build:
      context: .
      dockerfile: .docker/python/Dockerfile
    ports:
      - ${PYTHON_DOCKER_PORT}:${PYTHON_PORT}
    depends_on:
      - mongo
    volumes:
      - .:/code
  mongo:
    image: mongo
    ports:
      - ${DB_DOCKER_PORT}:${DB_PORT}
    volumes:
      - mongo_data:/data/db
volumes:
  mongo_data:
